### PR TITLE
Drop Exclude Fields support and use Fields 

### PR DESCRIPTION
**Pull request by panosangelopoulos**
Currently, the library only supports exclude fields, but this seems extremely dangerous because whenever a new field is added to the user model, we have to remember to exclude it in the settings, it is more than likely that we forget this and the field is exposed to public by accident.

To prevent this, with the current PR we will support `fields` on the `Meta` class of the `UserNode`, which is read from the new setting `USER_NODE_FIELDS`.

The whitelist approach is much safer as using only exclude fields.

### CODE REVIEW

**Comment by PedroBern** [comment]
**You are totally right!** But I think we should drop completely the `exclude fields`. I didn't understand why you revert it on the second commit. Maybe would be better to do this o `v0.4`, since it would drop a settings. I plan to discuss some `v0.4` features on #23, I'm just not into it yet because my time is very short right now, but I'm really looking forward to it.

**Comment by panosangelopoulos** [comment]
@PedroBern thanks for approving it! I can completely drop the `exclude` fields but first I would like to discuss it with you. Of course, if it's ok then I can add a new commit where I will remove it.

**Comment by PedroBern** [comment]
I thank you for the PR! You know what you are doing, you can do all the necessary changes to make it work. I've just created the v0.4 branch, please make the PR for it. Also, would be great if you can update the documentation about the new changes :)

**Comment by panosangelopoulos** [comment]
Sure thing, @PedroBern! Changed the base branch and update the docs accordingly.

**Pull request merged**
