### PR TITLE
Remove deprecated Django 2.1 support

### PR DESCRIPTION
**Pull request by ulgens**

### CODE REVIEW

**Comment by PedroBern** [comment]
Will let it open and merge for later for the v0.4

**Comment by ulgens** [comment]
@PedroBern It's going to be a year soon 🙂

**Comment by PedroBern** [comment]
@ulgens yes you are right! We need actually to support Django 3.x, the tests are failing, I didn't have the time to look over it yet.

**Comment by PedroBern** [comment]
edit: @ulgens I just saw, it's not failing for Django 3.x! 😅  My mistake

**Pull request merged**
