### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by cjfd481980**
Hi, I was using the library, but when I tend to install _django-graphql-social-auth[jwt]_

this error came:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
**django-graphql-auth 0.3.16 requires PyJWT<2.0.0, but you have pyjwt 2.0.1 which is incompatible.**

### CODE REVIEW

**Comment by PedroBern** [comment]
Hi, thanks for thw pr, but this package is not compatible with pyjwt v2

**Comment by panosangelopoulos** [comment]
Hi @cjfd481980 thanks for your effort and your PR but as @PedroBern mentioned this package is incompatible with pyjwt v2 and the ci check is failing.

I will close this PR in the next 3 days.

**Comment by ulgens** [comment]
grahpql-jwt package released another version last week. I think it may worth a try.

**Comment by panosangelopoulos** [comment]
Hi @cjfd481980 ! 

Do you have time to update your PR based on @ulgens comment? If not @ulgens, what do you think if we will provide a new PR and try it out?

**Pull request closed without merging**
