### PR TITLE
Added 'me' query

### PR DESCRIPTION
**Pull request by pors**

### CODE REVIEW

**Comment by pors** [comment]
PR for #13

**Comment by pors** [comment]
PS `make test-file p=38 f=query` throws errors for me.

**Comment by pors** [comment]
No time for docs now, I might have at the weekend. Anyway, better to have to code approved by you first :)

**Comment by pors** [comment]
@PedroBern please have a look. I also added some documentation.

**Comment by PedroBern** [comment]
It's perfect! Also thanks for correcting some typos I made!

**Pull request merged**
